<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Spring Modernized Dress Set', 
                'description' => 'Modernized dress set, elegant and youthful design, perfect for an energetic spring.',
                'price' => 264.60,
                'stock' => 100,
                'category_id' => 2, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Traditional Hanfu in Soft Pink', 
                'description' => 'Traditional Hanfu in soft pink, highlighting classic beauty.',
                'price' => 300.00,
                'stock' => 50,
                'category_id' => 3, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Sailor Dress', 
                'description' => 'Sailor dress with a full skirt, naturally voluminous, creating a perfect look.',
                'price' => 320.00,
                'stock' => 75,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Princess Dress with Elegant Bows', 
                'description' => 'Princess dress decorated with cute bows, offering a delicate and elegant look.',
                'price' => 450.00,
                'stock' => 60,
                'category_id' => 5, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sunshine Yellow Lolita Dress', 
                'description' => 'Bright yellow Lolita dress with a sweet and cute style, suitable for any occasion.',
                'price' => 350.00,
                'stock' => 80,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Pink Hanfu', 
                'description' => 'Elegant pink Hanfu design, perfect for formal events.',
                'price' => 400.00,
                'stock' => 40,
                'category_id' => 3, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Refreshing Green Hanfu', 
                'description' => 'Green Hanfu offering a fresh and graceful feeling.',
                'price' => 380.00,
                'stock' => 30,
                'category_id' => 3, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pure White Hanfu', 
                'description' => 'Pure white Hanfu representing purity and grace.',
                'price' => 500.00,
                'stock' => 50,
                'category_id' => 3, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Short Hanfu', 
                'description' => 'Modern short Hanfu with fine cuts, offering a distinct yet traditional look.',
                'price' => 280.00,
                'stock' => 60,
                'category_id' => 3, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japanese Style Lolita Dress', 
                'description' => 'Lolita dress inspired by Japanese style, feminine and elegant.',
                'price' => 350.00,
                'stock' => 70,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Charming Pink Chinese Lolita Dress', 
                'description' => 'Lolita dress blending Chinese style with a charming pink color, a mix of tradition and modernity.',
                'price' => 420.00,
                'stock' => 90,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bold Red Chinese Lolita Dress', 
                'description' => 'Chinese-inspired red Lolita dress, symbolizing strength and allure.',
                'price' => 430.00,
                'stock' => 50,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Black and Pink Chinese Lolita Dress', 
                'description' => 'Black and pink Chinese Lolita dress representing both classic and modern styles.',
                'price' => 450.00,
                'stock' => 40,
                'category_id' => 4, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frieren Cosplay Costume from Anime', 
                'description' => 'Cosplay costume of Frieren from the popular anime, featuring intricate details and craftsmanship.',
                'price' => 500.00,
                'stock' => 20,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kaname Madoka Cosplay Costume', 
                'description' => 'Cosplay costume of Kaname Madoka with exquisite design, capturing the mystical essence from the anime.',
                'price' => 550.00,
                'stock' => 25,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sakura Pink Cosplay Costume', 
                'description' => 'Cosplay costume inspired by Sakura, with a soft pink hue, a fluffy design, and lace details, perfect for cosplay events or photoshoots.',
                'price' => 480.00,
                'stock' => 30,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sakura Yellow Cosplay Costume', 
                'description' => 'Sakura cosplay costume in bright yellow, offering warmth and energy, made with soft, breathable fabric.',
                'price' => 490.00,
                'stock' => 25,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anya Cosplay Costume', 
                'description' => 'Cosplay costume of Anya Forger from Spy x Family, featuring a cute design with a golden trimmed collar and signature details.',
                'price' => 520.00,
                'stock' => 20,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nezuko Kamado Cosplay Costume', 
                'description' => 'Cosplay of Nezuko Kamado from Demon Slayer, featuring a pink kimono with geometric patterns and accessories to complete the look.',
                'price' => 550.00,
                'stock' => 35,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shinobu Kocho Cosplay Costume', 
                'description' => 'Shinobu Kocho cosplay, with a long kimono and butterfly design, embodying the elegance and mystery of the character.',
                'price' => 530.00,
                'stock' => 40,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nilou Cosplay Costume from Genshin Impact', 
                'description' => 'Nilou cosplay costume from Genshin Impact, featuring Persian-inspired designs and golden accents, a luxurious and captivating look.',
                'price' => 580.00,
                'stock' => 20,
                'category_id' => 1, 
                'created_at' => now(),
                'updated_at' => now(),
            ],            
            [
                'name' => 'Cosplay Costume of Navia', 
                'description' => 'A costume inspired by the character Navia, a strong and elegant warrior from Genshin Impact. The design reflects nobility with luxurious golden details and intricate embroidered lace, capturing the character’s authoritative charm.',
                'price' => 590.00,
                'stock' => 15,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cosplay Costume of Scaramouche', 
                'description' => 'The costume of Scaramouche, the charismatic antagonist from Genshin Impact. The design features royal elements with dark, warm colors, mysterious patterns, and the signature wide-brimmed hat, perfectly representing Scaramouche\'s enigmatic and cold persona.',
                'price' => 600.00,
                'stock' => 30,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cosplay Costume of Ayaka', 
                'description' => 'Kamisato Ayaka\'s cosplay costume from Genshin Impact, embodying the beauty of a noble lady. The kimono is intricately designed with delicate floral patterns and light armor, creating a graceful yet powerful image of the character.',
                'price' => 610.00,
                'stock' => 25,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cosplay Costume of Ganyu', 
                'description' => 'Cosplay costume of Ganyu, one of the most beloved characters in Genshin Impact. The costume features a soft blue color, with delicate, intricate patterns, reflecting Ganyu’s graceful and gentle nature while still exuding strength.',
                'price' => 620.00,
                'stock' => 40,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Green', 
                'description' => 'Green Lolita dress with a classic style, designed with high-quality lace fabric and delicate floral patterns, creating a feminine and elegant look while still being unique.',
                'price' => 340.00,
                'stock' => 60,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unique Blue Lolita', 
                'description' => 'Gothic Lolita dress with traditional elements, featuring dark tones such as black, deep red, or navy blue. The intricate design includes layered skirts, a large bow at the back, and finely detailed lace, creating a mysterious yet alluring beauty.',
                'price' => 350.00,
                'stock' => 80,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Blue Style', 
                'description' => 'Lolita dress combining Chinese style with traditional patterns like dragons, lotuses, and hand-embroidered lines. The premium fabric enhances the luxurious, noble appearance.',
                'price' => 360.00,
                'stock' => 75,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sakya Lolita', 
                'description' => 'Sakya style Lolita dress, exuding a regal and graceful beauty.',
                'price' => 380.00,
                'stock' => 50,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita and Chinese Style', 
                'description' => 'Lolita dress combined with Chinese elements, creating a perfect blend of modern and classical styles.',
                'price' => 400.00,
                'stock' => 65,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Sky', 
                'description' => 'Blue Lolita dress with a soft, elegant style.',
                'price' => 420.00,
                'stock' => 40,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pink Hanbok', 
                'description' => 'Pink Hanbok, a traditional Korean costume with vibrant colors.',
                'price' => 500.00,
                'stock' => 45,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita and Folk Culture Elements', 
                'description' => 'Lolita dress combined with folk culture elements, offering a unique and traditional beauty.',
                'price' => 430.00,
                'stock' => 30,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hanfu', 
                'description' => 'Traditional Hanfu costume, rich in Chinese cultural heritage.',
                'price' => 550.00,
                'stock' => 60,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Red Female Modernized Costume', 
                'description' => 'Modernized female red costume, blending traditional and contemporary styles for formal occasions.',
                'price' => 580.00,
                'stock' => 40,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Modern Traditional Costume', 
                'description' => 'Modernized traditional costume, combining new trends with classic style.',
                'price' => 590.00,
                'stock' => 35,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Contemporary Traditional Costume', 
                'description' => 'Modernized traditional costume with a contemporary design influenced by traditional attire.',
                'price' => 600.00,
                'stock' => 50,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Modernized Costume', 
                'description' => 'Traditional modernized costume combining elements of the old and new.',
                'price' => 620.00,
                'stock' => 45,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],            
            [
                'name' => 'Traditional Hmong Costume', 
                'description' => 'Trang phục truyền thống của người H\'Mông, mang đậm bản sắc dân tộc.',
                'price' => 640.00,
                'stock' => 30,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Extremely Impressive Modern Gothic Lolita', 
                'description' => 'Váy Gothic Lolita cách tân, mang đậm phong cách Gothic với sự kết hợp hiện đại.',
                'price' => 650.00,
                'stock' => 50,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gorgeous Princess Dress for Every Occasion', 
                'description' => 'Đầm công chúa sang trọng, thiết kế nữ tính và lộng lẫy.',
                'price' => 680.00,
                'stock' => 60,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mysterious Black Witch', 
                'description' => 'Trang phục phù thủy, phong cách bí ẩn và huyền bí.',
                'price' => 670.00,
                'stock' => 45,
                'category_id' =>4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Pink Cute', 
                'description' => 'Váy Lolita màu hồng, phong cách dễ thương và nữ tính.',
                'price' => 360.00,
                'stock' => 70,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đầm Pink Feminine Ttyle ', 
                'description' => 'Đầm hồng dịu dàng, phù hợp cho các dịp trang trọng.',
                'price' => 370.00,
                'stock' => 65,
                'category_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Blue Elegant', 
                'description' => 'Váy Lolita màu xanh, tạo cảm giác thanh thoát và dễ chịu.',
                'price' => 380.00,
                'stock' => 55,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Blue Bright', 
                'description' => 'Váy Lolita màu xanh, mang lại vẻ đẹp nhẹ nhàng và duyên dáng.',
                'price' => 390.00,
                'stock' => 60,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Yellow Shine ', 
                'description' => 'Váy Lolita màu vàng, tạo nên phong cách tươi mới và nổi bật.',
                'price' => 400.00,
                'stock' => 50,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Pink Tender', 
                'description' => 'Váy Lolita màu hồng, mang đến sự ngọt ngào và nữ tính.',
                'price' => 420.00,
                'stock' => 75,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Black Mystery', 
                'description' => 'Váy Lolita màu đen, phong cách Gothic nhẹ nhàng.',
                'price' => 430.00,
                'stock' => 45,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Pink Bow Tie ', 
                'description' => 'Váy Lolita với thiết kế đặc biệt, nhấn mạnh vòng eo.',
                'price' => 440.00,
                'stock' => 50,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lolita Pink Special', 
                'description' => 'Váy Lolita màu hồng, tôn lên vẻ nữ tính và dịu dàng.',
                'price' => 450.00,
                'stock' => 65,
                'category_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
        
    }
}
